name: constellationbot

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - ipython
  - jupyter
  - pandas
  - matplotlib
  - scipy
  - pillow
  - astropy
  - poliastro
  - jplephem
  - xlsxwriter
  - wheel
  - seaborn  
  - numba  
  - numpy  
  - pip:
    - datetime  
    - spacetrack 
    - sgp4  
