name: Generate GIFs

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLTRACK_PWD: ${{ secrets.SLTRACK_PWD }}
      SLTRACK_USR: ${{ secrets.SLTRACK_USR }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Miniconda
      uses: actions/cache@v2
      with:
        path: ~/miniconda3/envs/constellationbot
        key: ${{ runner.os }}-constellationbot-${{ hashFiles('config/constellationbot_env.yml') }}
        restore-keys: |
          ${{ runner.os }}-constellationbot-

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: constellationbot
        environment-file: config/constellationbot_env.yml
        auto-activate-base: false

    - name: Debug
      run: |
        which python
        conda list -n constellationbot
        conda info --envs

    - name: Activate and Run
      run: |
        eval "$(conda shell.bash hook)"
        conda activate constellationbot
        python -m source.visualisation_maker.constellation_gifs 

    - name: Determine the absolute latest GIF
      run: |
        echo "LATEST_GIF=$(find images/constellation_anim/* -type f | xargs ls -t | head -n 1)" >> $GITHUB_ENV

    - name: Upload GIFs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: gifs
        path: ${{ env.LATEST_GIF }}

    - name: Get artifact URL
      id: get_url
      run: |
        ARTIFACT_URL=$(curl -H "Authorization: token ${PERSONAL_ACCESS_TOKEN}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/CharlesPlusC/ConstellationBot/actions/artifacts | \
                            jq '.artifacts[0].archive_download_url' -r)
        echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Print ARTIFACT_URL for Debugging
      run: echo $ARTIFACT_URL
      env:
        ARTIFACT_URL: ${{ env.ARTIFACT_URL }}

    - name: Trigger Website Update Workflow
      run: |
        curl -X POST \
             -H "Authorization: token ${PERSONAL_ACCESS_TOKEN}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/CharlesPlusC/CharlesPlusC.github.io/dispatches \
             -d "{\"event_type\":\"update-gifs\", \"client_payload\": {\"artifact_url\": \"$ARTIFACT_URL\"}}"
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        ARTIFACT_URL: ${{ env.ARTIFACT_URL }}
