name: Generate GIFs

on:
  schedule:
    # This runs every day at 7AM UTC.
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        conda env create -f config/constellationbot_env.yml
        conda activate constellationbot

    - name: Generate GIFs
      run: |
        python -m source.visualisation_maker.constellation_gifs 

    - name: Upload GIFs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: gifs
        path: images/constellation_anim/gifs*
